name:         Ganglia-GMetric
version:      0.3
version_from: lib/Ganglia/Gmetric.pm
installdirs:  site
requires:
    Class::Accessor:         0.31
    IO::CaptureOutput:         1.0801
distribution_type: module
